#!/bin/bash

#text=$(man bash)

man bash | tr -cs A-Za-z\' '\n' |         
  tr A-Z a-z |                 
    sort |                     
      uniq -c |                
        sort -k1,1nr -k2 |     
          sed ${1:-3}q        
